### ISSUE TITLE
irmeasure~-help.pd

### ISSUE THREAD

**Issue by grammaton** [d-i-s/piro#2]
- [s~ loop] lo capisco, ma credo che in generale un'indicazione, un commento, su come indirizzare i segnali per un ir verso dac~ sia necessaria, magari con un patch differente da help
 - il commento dello sweep riporta una durata di 30 secondi mentre lo sweep generato è un breve chirp da 200ms
 - is egnali generati non sono fullscale. il che ci sta, ma andrebbe specificato che attualmente sono a -1dB. forse un'attenuazione di 3dB sarebbe più facile da gestire, ma in ogni caso andrebbe spiegata. Io mi aspetterei di vedere tutto rosso. e attenuando .5 di vedere -6dB sul meter in luogo degli attuali -7dB

**Comment by d-i-s** [comment]
- updated the helpfile; a tutorial patch may be possible in the future;
- updated the helpfile;
- added the fullscale method and set to 0 dB the default amplitude.
